name: Bump major version

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run semantic-release version --major --skip-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONPATH: .
